name: harvest
version: 2.0.8
author: Lars Tackmann <lars@solvr.io>
description: Event store for Dart with multiple backends
homepage: https://github.com/ltackmann/harvest
environment:
  sdk: '>=1.9.0 <2.0.0'
dependencies:
  log4dart: any
  serialization: any
  uuid: any
dev_dependencies:
  polymer: any
  route_hierarchical: any
  test: any
transformers:
- polymer:
    entry_points:
     - test/harvest_idb_test.html
